INSERT INTO continents VALUES (1, "North America");
INSERT INTO continents VALUES (2, "South America");
INSERT INTO continents VALUES (3, "Europe");
INSERT INTO continents VALUES (4, "Africa");
INSERT INTO continents VALUES (5, "Asia");
INSERT INTO continents VALUES (6, "Oceania");
INSERT INTO countries VALUES( 1, 1, "Canada");
INSERT INTO countries VALUES( 2, 1, "Cuba");
INSERT INTO countries VALUES( 3, 1, "Mexico");
INSERT INTO countries VALUES( 4, 1, "United States of America");
INSERT INTO countries VALUES( 5, 2, "Argentina");
INSERT INTO countries VALUES( 6, 2, "Brazil");
INSERT INTO countries VALUES( 7, 2, "Chile");
INSERT INTO countries VALUES( 8, 2, "Colombia");
INSERT INTO countries VALUES( 9, 2, "Ecuador");
INSERT INTO countries VALUES(10, 2, "Paraguay");
INSERT INTO countries VALUES(11, 2, "Peru");
INSERT INTO countries VALUES(12, 2, "Uruguay");
INSERT INTO countries VALUES(13, 2, "Venezuela");
INSERT INTO countries VALUES(14, 3, "Austria");
INSERT INTO countries VALUES(15, 3, "Belgium");
INSERT INTO countries VALUES(16, 3, "Bulgaria");
INSERT INTO countries VALUES(17, 3, "Croatia");
INSERT INTO countries VALUES(18, 3, "Czech Republic");
INSERT INTO countries VALUES(19, 3, "Denmark");
INSERT INTO countries VALUES(20, 3, "Estonia");
INSERT INTO countries VALUES(21, 3, "Finland");
INSERT INTO countries VALUES(22, 3, "France");
INSERT INTO countries VALUES(23, 3, "Germany");
INSERT INTO countries VALUES(24, 3, "Greece");
INSERT INTO countries VALUES(25, 3, "Hungary");
INSERT INTO countries VALUES(26, 3, "Ireland");
INSERT INTO countries VALUES(27, 3, "Italy");
INSERT INTO countries VALUES(28, 3, "Kosovo");
INSERT INTO countries VALUES(29, 3, "Latvia");
INSERT INTO countries VALUES(30, 3, "Liechtenstein");
INSERT INTO countries VALUES(31, 3, "Lithuania");
INSERT INTO countries VALUES(32, 3, "Macedonia");
INSERT INTO countries VALUES(33, 3, "Montenegro");
INSERT INTO countries VALUES(34, 3, "Netherlands");
INSERT INTO countries VALUES(35, 3, "Norway");
INSERT INTO countries VALUES(36, 3, "Poland");
INSERT INTO countries VALUES(37, 3, "Portugal");
INSERT INTO countries VALUES(38, 3, "Romania");
INSERT INTO countries VALUES(39, 3, "Serbia");
INSERT INTO countries VALUES(40, 3, "Slovakia");
INSERT INTO countries VALUES(41, 3, "Slovenia");
INSERT INTO countries VALUES(42, 3, "Spain");
INSERT INTO countries VALUES(43, 3, "Sweden");
INSERT INTO countries VALUES(44, 3, "Switzerland");
INSERT INTO countries VALUES(45, 3, "United Kingdom");
INSERT INTO countries VALUES(46, 4, "Angola");
INSERT INTO countries VALUES(47, 4, "Botswana");
INSERT INTO countries VALUES(48, 4, "Cameroon");
INSERT INTO countries VALUES(49, 4, "Central African Republic");
INSERT INTO countries VALUES(50, 4, "Congo");
INSERT INTO countries VALUES(51, 4, "Egypt");
INSERT INTO countries VALUES(52, 4, "Ethiopia");
INSERT INTO countries VALUES(53, 4, "Gabon");
INSERT INTO countries VALUES(54, 4, "Ghana");
INSERT INTO countries VALUES(55, 4, "Kenya");
INSERT INTO countries VALUES(56, 4, "Libya");
INSERT INTO countries VALUES(57, 4, "Morocco");
INSERT INTO countries VALUES(58, 4, "Mozambique");
INSERT INTO countries VALUES(59, 4, "Nigeria");
INSERT INTO countries VALUES(60, 4, "Senegal");
INSERT INTO countries VALUES(61, 5, "Azerbaijan");
INSERT INTO countries VALUES(62, 5, "Bangladesh");
INSERT INTO countries VALUES(63, 5, "Cambodia");
INSERT INTO countries VALUES(64, 5, "China");
INSERT INTO countries VALUES(65, 5, "India");
INSERT INTO countries VALUES(66, 5, "Indonesia");
INSERT INTO countries VALUES(67, 5, "Japan");
INSERT INTO countries VALUES(68, 5, "Kazakhstan");
INSERT INTO countries VALUES(69, 5, "Malaysia");
INSERT INTO countries VALUES(70, 5, "Mongolia");
INSERT INTO countries VALUES(71, 5, "Nepal");
INSERT INTO countries VALUES(72, 5, "Pakistan");
INSERT INTO countries VALUES(73, 5, "Philippines");
INSERT INTO countries VALUES(74, 5, "South Korea");
INSERT INTO countries VALUES(75, 5, "Taiwan");
INSERT INTO countries VALUES(76, 5, "Thailand");
INSERT INTO countries VALUES(77, 5, "Vietnam");
INSERT INTO countries VALUES(78, 6, "Australia");
INSERT INTO countries VALUES(79, 6, "New Zealand");
INSERT INTO cities VALUES(  1, 59, "Abuja");
INSERT INTO cities VALUES(  2, 54, "Accra");
INSERT INTO cities VALUES(  3, 52, "Addis Ababa");
INSERT INTO cities VALUES(  4, 34, "Amsterdam");
INSERT INTO cities VALUES(  5, 68, "Astana");
INSERT INTO cities VALUES(  6, 10, "Asuncion");
INSERT INTO cities VALUES(  7, 24, "Athens");
INSERT INTO cities VALUES(  8, 61, "Baku");
INSERT INTO cities VALUES(  9, 76, "Bangkok");
INSERT INTO cities VALUES( 10, 49, "Bangui");
INSERT INTO cities VALUES( 11, 42, "Barcelona");
INSERT INTO cities VALUES( 12, 44, "Basel");
INSERT INTO cities VALUES( 13, 64, "Beijing");
INSERT INTO cities VALUES( 14, 39, "Belgrade");
INSERT INTO cities VALUES( 15, 23, "Berlin");
INSERT INTO cities VALUES( 16, 44, "Bern");
INSERT INTO cities VALUES( 17, 45, "Birmingham");
INSERT INTO cities VALUES( 18,  8, "Bogota");
INSERT INTO cities VALUES( 19, 65, "Bombay");
INSERT INTO cities VALUES( 20, 23, "Bonn");
INSERT INTO cities VALUES( 21, 38, "Brasov");
INSERT INTO cities VALUES( 22, 40, "Bratislava");
INSERT INTO cities VALUES( 23, 45, "Bristol");
INSERT INTO cities VALUES( 24, 15, "Brussels");
INSERT INTO cities VALUES( 25, 38, "Bucharest");
INSERT INTO cities VALUES( 26, 25, "Budapest");
INSERT INTO cities VALUES( 27,  5, "Buenos Aires");
INSERT INTO cities VALUES( 28, 51, "Cairo");
INSERT INTO cities VALUES( 29, 45, "Cambridge");
INSERT INTO cities VALUES( 30, 78, "Canberra");
INSERT INTO cities VALUES( 31, 13, "Caracas");
INSERT INTO cities VALUES( 32,  4, "Chicago");
INSERT INTO cities VALUES( 33, 38, "Cluj");
INSERT INTO cities VALUES( 34, 19, "Copenhagen");
INSERT INTO cities VALUES( 35, 45, "Coventry");
INSERT INTO cities VALUES( 36, 60, "Dakar");
INSERT INTO cities VALUES( 37, 62, "Dhaka");
INSERT INTO cities VALUES( 38, 26, "Dublin");
INSERT INTO cities VALUES( 39, 27, "Firenze");
INSERT INTO cities VALUES( 40, 23, "Frankfurt");
INSERT INTO cities VALUES( 41, 47, "Gaborone");
INSERT INTO cities VALUES( 42, 45, "Glasgow");
INSERT INTO cities VALUES( 43, 45, "Gloucester");
INSERT INTO cities VALUES( 44, 14, "Graz");
INSERT INTO cities VALUES( 45, 64, "Guangzhou");
INSERT INTO cities VALUES( 46, 23, "Hamburg");
INSERT INTO cities VALUES( 47, 77, "Hanoi");
INSERT INTO cities VALUES( 48,  2, "Havana");
INSERT INTO cities VALUES( 49, 21, "Helsinki");
INSERT INTO cities VALUES( 50,  4, "Houston");
INSERT INTO cities VALUES( 51, 72, "Islamabad");
INSERT INTO cities VALUES( 52, 66, "Jakarta");
INSERT INTO cities VALUES( 53, 72, "Karachi");
INSERT INTO cities VALUES( 54, 71, "Kathmandu");
INSERT INTO cities VALUES( 55, 50, "Kinshasa");
INSERT INTO cities VALUES( 56, 69, "Kuala Lumpur");
INSERT INTO cities VALUES( 57, 67, "Kyoto");
INSERT INTO cities VALUES( 58, 59, "Lagos");
INSERT INTO cities VALUES( 59, 53, "Libreville");
INSERT INTO cities VALUES( 60, 11, "Lima");
INSERT INTO cities VALUES( 61, 14, "Linz");
INSERT INTO cities VALUES( 62, 37, "Lisbon");
INSERT INTO cities VALUES( 63, 45, "Liverpool");
INSERT INTO cities VALUES( 64, 41, "Ljubljana");
INSERT INTO cities VALUES( 65, 45, "London");
INSERT INTO cities VALUES( 66,  4, "Los Angeles");
INSERT INTO cities VALUES( 67, 46, "Luanda");
INSERT INTO cities VALUES( 68, 42, "Madrid");
INSERT INTO cities VALUES( 69, 73, "Manila");
INSERT INTO cities VALUES( 70, 58, "Maputo");
INSERT INTO cities VALUES( 71,  3, "Mexico City");
INSERT INTO cities VALUES( 72, 27, "Milano");
INSERT INTO cities VALUES( 73, 12, "Montevideo");
INSERT INTO cities VALUES( 74, 65, "Mumbai");
INSERT INTO cities VALUES( 75, 23, "Munich");
INSERT INTO cities VALUES( 76, 67, "Nagoya");
INSERT INTO cities VALUES( 77, 55, "Nairobi");
INSERT INTO cities VALUES( 78, 65, "New Delhi");
INSERT INTO cities VALUES( 79,  4, "New York City");
INSERT INTO cities VALUES( 80, 45, "Newcastle");
INSERT INTO cities VALUES( 81, 45, "Nottingham");
INSERT INTO cities VALUES( 82, 67, "Osaka");
INSERT INTO cities VALUES( 83, 35, "Oslo");
INSERT INTO cities VALUES( 84,  1, "Ottawa");
INSERT INTO cities VALUES( 85, 45, "Oxford");
INSERT INTO cities VALUES( 86, 22, "Paris");
INSERT INTO cities VALUES( 87,  4, "Philadelphia");
INSERT INTO cities VALUES( 88, 63, "Phnom Penh");
INSERT INTO cities VALUES( 89, 33, "Podgorica");
INSERT INTO cities VALUES( 90, 18, "Prague");
INSERT INTO cities VALUES( 91, 28, "Pristina");
INSERT INTO cities VALUES( 92,  9, "Quito");
INSERT INTO cities VALUES( 93, 57, "Rabat");
INSERT INTO cities VALUES( 94, 29, "Riga");
INSERT INTO cities VALUES( 95,  6, "Rio de Janeiro");
INSERT INTO cities VALUES( 96, 27, "Rome");
INSERT INTO cities VALUES( 97, 14, "Salzburg");
INSERT INTO cities VALUES( 98,  4, "San Francisco");
INSERT INTO cities VALUES( 99,  7, "Santiago");
INSERT INTO cities VALUES(100,  6, "Sao Paolo");
INSERT INTO cities VALUES(101, 67, "Sapporo");
INSERT INTO cities VALUES(102, 74, "Seoul");
INSERT INTO cities VALUES(103, 64, "Shenzhen");
INSERT INTO cities VALUES(104, 38, "Sibiu");
INSERT INTO cities VALUES(105, 32, "Skopje");
INSERT INTO cities VALUES(106, 16, "Sofia");
INSERT INTO cities VALUES(107, 43, "Stockholm");
INSERT INTO cities VALUES(108, 75, "Taipei");
INSERT INTO cities VALUES(109, 20, "Tallinn");
INSERT INTO cities VALUES(110, 64, "Tianjin");
INSERT INTO cities VALUES(111, 38, "Timisoara");
INSERT INTO cities VALUES(112, 67, "Tokyo");
INSERT INTO cities VALUES(113, 27, "Torino");
INSERT INTO cities VALUES(114, 56, "Tripoli");
INSERT INTO cities VALUES(115, 70, "Ulaanbaatar");
INSERT INTO cities VALUES(116, 30, "Vaduz");
INSERT INTO cities VALUES(117, 14, "Vienna");
INSERT INTO cities VALUES(118, 31, "Vilnius");
INSERT INTO cities VALUES(119, 36, "Warsaw");
INSERT INTO cities VALUES(120, 79, "Wellington");
INSERT INTO cities VALUES(121, 48, "Yaounde");
INSERT INTO cities VALUES(122, 17, "Zagreb");
INSERT INTO cities VALUES(123, 44, "Zurich");

